body:
  - type: input
    id: duende_version
    attributes:
      label: "BFF version"
      description: "Which version of Duende BFF are you using?"
    validations:
      required: true
  - type: input
    id: dotnet_version
    attributes:
      label: ".NET version"
      description: "Which version of .NET are you using?"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the issue"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "Reproduction steps"
      description: "How do you trigger this issue? Please walk us through it step by step."
  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: "Log output/exception with stacktrace"
      render: bash
  - type: textarea
    id: context
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."