body:
  - type: input
    attributes:
      label: "Job title"
    validations:
      required: true
  - type: input
    attributes:
      label: "Location"
    validations:
      required: true
  - type: input
    attributes:
      label: "Company"
    validations:
      required: true
  - type: input
    attributes:
      label: "Company website"
      placeholder: "https://example.com"
    validations:
      required: true
  - type: markdown
    attributes:
      label: "Description"
      description: "Describe the job opportunity. Include relevant details, including whether remote work is allowed etc."
    validations:
      required: true
  - type: markdown
    attributes:
      label: "How to apply?"
      description: "How does one apply?"
  - type: markdown
    attributes:
      label: "Anything else?"
